---
slug: 2024-11-11-northsec-2024-by-romain
title: Northsec CTF 2024 - "Appendix"
date: 2024-11-11
authors: [romain]
tags: [web, nsec]
---

# Appendix

Ce writeup est √† propos du challenge "Appendix" de l'√©dition 2024 du Northsec CTF
<!-- truncate -->

This write-up was authored by one of our teammates [@RomainL972](https://github.com/RomainL972)! üéâ

## Recr√©ation du challenge

Pour tester ce challenge √† la maison, t√©l√©chargez les fichiers [flag.py](flag.py) et [script.py](script.py), puis lancez les commandes suivantes:

```bash
python -m venv env
source ./env/bin/activate
pip install flask requests
flask --app script run --debug
```

Le challenge sera alors disponible sur http://localhost:5000

## Exploration

En acc√©dant √† l'URL, on tombe sur un joli site web tout rose, comme on peut le voir ci-dessous:

![Screenshot](images/screenshot1.png)

Si on entre la valeur "test" dans le champ Destination et qu'on clique sur le bouton, on obtient comme r√©ponse:

```
Invalid destination: test
Message: Invalid URL 'test': No scheme supplied. Perhaps you meant https://test?
```

Si on ajoute le "https", on revient au message de d√©part.

Si on clique sur le bouton pronostic, on obtient le code source, une tr√®s bonne nouvelle quand on ne vient pas de le t√©l√©charger sur ce writeup!

## Analyse du code

On peut voir dans le code √† la ligne 43 que le serveur essaye de se connecter √† la valeur donn√©e dans "Destination", et si une premi√®re requ√™te HTTP envoy√©e re√ßoit une r√©ponse, une deuxi√®me est envoy√©e avec le flag dans le corps de la requ√™te.

Dans ce cas, on pourrait simplement ouvrir un serveur HTTP Python:

```
python3 -m http.server --bind :: 1234
```

Puis donner l'URL "http://localhost:1234/" au serveur.

Malheureusement, en faisant √ßa, on re√ßoit de nouveau le message d'accueil, et aucune requ√™te n'a √©t√© envoy√©e.

En cherchant un peu plus loin, on voit que la fonction "malfunction" est appel√©e pour modifier l'entr√©e avant de faire la requ√™te, peut-√™tre que le probl√®me vient de l√†...

En effet! Les appels √† urlsplit et urlunsplit suppriment tout ce qui est avant le "/" final de l'URL, c'est emb√™tant. J'essaye quelques combinaisons un peu √©tranges pour essayer de bypasser les fonctions, mais sans r√©sultat...

Par exemple, en mettant "/http://localhost:1234", avec un "/" au d√©but, on peut passthrough notre URL jusqu'√† la derni√®re √©tape, mais la requ√™te ne sera malheureusement pas ex√©cut√©e car "/http://" n'est pas un scheme valide.

## La faille !

En recherchant sur Google "CVE urlsplit", on tombe sur un article qui explique qu'il existe une vuln√©rabilit√© dans certaines versions de Python, o√π l'on peut entrer une URL avec un espace vide " " au tout d√©but, afin d'√©viter les filtres appliqu√©s sur le r√©sultat d'urlsplit.

L'article : https://medium.com/thesecmaster/how-to-fix-cve-2023-24329-url-parsing-issue-in-python-794018e4b57a#1005

Malheureusement, cette faille a √©t√© r√©par√©e sur la version utilis√©e sur le serveur, cette solution ne fonctionne donc pas.

En cherchant un peu plus, on peut trouver le code source d'urlsplit sur GitHub, et c'est en particulier le `url = url.lstrip(_WHATWG_C0_CONTROL_OR_SPACE)` ([lien](https://github.com/python/cpython/blob/be257c58152e9b960827362b11c9ef2223fd6267/Lib/urllib/parse.py#L477)) qui nous int√©resse. En effet, les espaces et les caract√®res de contr√¥les sont enlev√©s, mais pas les autres caract√®res Unicode.

En s'inspirant de la faille pr√©sent√©e et du code source de Python, on peut essayer une variante similaire, en ins√©rant au d√©but de l'URL le caract√®re [Unicode demi-espace U+2009](https://www.compart.com/en/unicode/U+2009). On met donc comme payload "&ThinSpace;http://localhost:1234" o√π le premier caract√®re est un demi espace.

On obtient alors le message "Beneficial bacterias successfully delivered.", et le flag s'affiche dans notre console !!

![R√©sultat final](images/result.png)
